# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countrylatency_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countrylatency_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x63ountrylatency_service.proto\"@\n\x15\x43ountryLatencyRequest\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x11\n\tmean\x18\x02 \x01(\x08\"u\n\x0e\x43ountryLatency\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61te_request\x18\x03 \x01(\t\x12\x10\n\x08isp_name\x18\x04 \x01(\t\x12\x0f\n\x07latency\x18\x05 \x01(\t\"A\n\x16\x43ountryLatencyResponse\x12\'\n\x0e\x63ountryLatency\x18\x01 \x03(\x0b\x32\x0f.CountryLatency2^\n\x15\x43ountryLatencyService\x12\x45\n\x12\x43ountryLatencyInfo\x12\x16.CountryLatencyRequest\x1a\x17.CountryLatencyResponseb\x06proto3'
)




_COUNTRYLATENCYREQUEST = _descriptor.Descriptor(
  name='CountryLatencyRequest',
  full_name='CountryLatencyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryLatencyRequest.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='CountryLatencyRequest.mean', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=96,
)


_COUNTRYLATENCY = _descriptor.Descriptor(
  name='CountryLatency',
  full_name='CountryLatency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryLatency.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='CountryLatency.country_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_request', full_name='CountryLatency.date_request', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isp_name', full_name='CountryLatency.isp_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latency', full_name='CountryLatency.latency', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=215,
)


_COUNTRYLATENCYRESPONSE = _descriptor.Descriptor(
  name='CountryLatencyResponse',
  full_name='CountryLatencyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='countryLatency', full_name='CountryLatencyResponse.countryLatency', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=282,
)

_COUNTRYLATENCYRESPONSE.fields_by_name['countryLatency'].message_type = _COUNTRYLATENCY
DESCRIPTOR.message_types_by_name['CountryLatencyRequest'] = _COUNTRYLATENCYREQUEST
DESCRIPTOR.message_types_by_name['CountryLatency'] = _COUNTRYLATENCY
DESCRIPTOR.message_types_by_name['CountryLatencyResponse'] = _COUNTRYLATENCYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryLatencyRequest = _reflection.GeneratedProtocolMessageType('CountryLatencyRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYLATENCYREQUEST,
  '__module__' : 'countrylatency_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryLatencyRequest)
  })
_sym_db.RegisterMessage(CountryLatencyRequest)

CountryLatency = _reflection.GeneratedProtocolMessageType('CountryLatency', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYLATENCY,
  '__module__' : 'countrylatency_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryLatency)
  })
_sym_db.RegisterMessage(CountryLatency)

CountryLatencyResponse = _reflection.GeneratedProtocolMessageType('CountryLatencyResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYLATENCYRESPONSE,
  '__module__' : 'countrylatency_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryLatencyResponse)
  })
_sym_db.RegisterMessage(CountryLatencyResponse)



_COUNTRYLATENCYSERVICE = _descriptor.ServiceDescriptor(
  name='CountryLatencyService',
  full_name='CountryLatencyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=284,
  serialized_end=378,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountryLatencyInfo',
    full_name='CountryLatencyService.CountryLatencyInfo',
    index=0,
    containing_service=None,
    input_type=_COUNTRYLATENCYREQUEST,
    output_type=_COUNTRYLATENCYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTRYLATENCYSERVICE)

DESCRIPTOR.services_by_name['CountryLatencyService'] = _COUNTRYLATENCYSERVICE

# @@protoc_insertion_point(module_scope)
