# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countryspeeds_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countryspeeds_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1b\x63ountryspeeds_service.proto\"?\n\x14\x43ountrySpeedsRequest\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x11\n\tmean\x18\x02 \x01(\x08\"\x7f\n\rCountrySpeeds\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x61te_request\x18\x03 \x01(\t\x12\x16\n\x0e\x64ownload_speed\x18\x04 \x01(\t\x12\x14\n\x0cupload_speed\x18\x05 \x01(\t\">\n\x15\x43ountrySpeedsResponse\x12%\n\rcountrySpeeds\x18\x01 \x03(\x0b\x32\x0e.CountrySpeeds2Z\n\x14\x43ountrySpeedsService\x12\x42\n\x11\x43ountrySpeedsInfo\x12\x15.CountrySpeedsRequest\x1a\x16.CountrySpeedsResponseb\x06proto3'
)




_COUNTRYSPEEDSREQUEST = _descriptor.Descriptor(
  name='CountrySpeedsRequest',
  full_name='CountrySpeedsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountrySpeedsRequest.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='CountrySpeedsRequest.mean', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=94,
)


_COUNTRYSPEEDS = _descriptor.Descriptor(
  name='CountrySpeeds',
  full_name='CountrySpeeds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountrySpeeds.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='CountrySpeeds.country_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_request', full_name='CountrySpeeds.date_request', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_speed', full_name='CountrySpeeds.download_speed', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_speed', full_name='CountrySpeeds.upload_speed', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=223,
)


_COUNTRYSPEEDSRESPONSE = _descriptor.Descriptor(
  name='CountrySpeedsResponse',
  full_name='CountrySpeedsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='countrySpeeds', full_name='CountrySpeedsResponse.countrySpeeds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=287,
)

_COUNTRYSPEEDSRESPONSE.fields_by_name['countrySpeeds'].message_type = _COUNTRYSPEEDS
DESCRIPTOR.message_types_by_name['CountrySpeedsRequest'] = _COUNTRYSPEEDSREQUEST
DESCRIPTOR.message_types_by_name['CountrySpeeds'] = _COUNTRYSPEEDS
DESCRIPTOR.message_types_by_name['CountrySpeedsResponse'] = _COUNTRYSPEEDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountrySpeedsRequest = _reflection.GeneratedProtocolMessageType('CountrySpeedsRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYSPEEDSREQUEST,
  '__module__' : 'countryspeeds_service_pb2'
  # @@protoc_insertion_point(class_scope:CountrySpeedsRequest)
  })
_sym_db.RegisterMessage(CountrySpeedsRequest)

CountrySpeeds = _reflection.GeneratedProtocolMessageType('CountrySpeeds', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYSPEEDS,
  '__module__' : 'countryspeeds_service_pb2'
  # @@protoc_insertion_point(class_scope:CountrySpeeds)
  })
_sym_db.RegisterMessage(CountrySpeeds)

CountrySpeedsResponse = _reflection.GeneratedProtocolMessageType('CountrySpeedsResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYSPEEDSRESPONSE,
  '__module__' : 'countryspeeds_service_pb2'
  # @@protoc_insertion_point(class_scope:CountrySpeedsResponse)
  })
_sym_db.RegisterMessage(CountrySpeedsResponse)



_COUNTRYSPEEDSSERVICE = _descriptor.ServiceDescriptor(
  name='CountrySpeedsService',
  full_name='CountrySpeedsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=289,
  serialized_end=379,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountrySpeedsInfo',
    full_name='CountrySpeedsService.CountrySpeedsInfo',
    index=0,
    containing_service=None,
    input_type=_COUNTRYSPEEDSREQUEST,
    output_type=_COUNTRYSPEEDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTRYSPEEDSSERVICE)

DESCRIPTOR.services_by_name['CountrySpeedsService'] = _COUNTRYSPEEDSSERVICE

# @@protoc_insertion_point(module_scope)
