# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cityspeeds_service_pb2 as cityspeeds__service__pb2


class CitySpeedsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CitySpeedsInfo = channel.unary_unary(
                '/CitySpeedsService/CitySpeedsInfo',
                request_serializer=cityspeeds__service__pb2.CitySpeedsRequest.SerializeToString,
                response_deserializer=cityspeeds__service__pb2.CitySpeedsResponse.FromString,
                )


class CitySpeedsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CitySpeedsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CitySpeedsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CitySpeedsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CitySpeedsInfo,
                    request_deserializer=cityspeeds__service__pb2.CitySpeedsRequest.FromString,
                    response_serializer=cityspeeds__service__pb2.CitySpeedsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CitySpeedsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CitySpeedsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CitySpeedsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CitySpeedsService/CitySpeedsInfo',
            cityspeeds__service__pb2.CitySpeedsRequest.SerializeToString,
            cityspeeds__service__pb2.CitySpeedsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
