# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cityspeeds_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cityspeeds_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x63ityspeeds_service.proto\"9\n\x11\x43itySpeedsRequest\x12\x11\n\tcity_name\x18\x01 \x01(\t\x12\x11\n\tmean\x18\x02 \x01(\x08\"\xb6\x01\n\nCitySpeeds\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x11\n\tcity_name\x18\x03 \x01(\t\x12\x13\n\x0bregion_code\x18\x04 \x01(\t\x12\x10\n\x08isp_name\x18\x05 \x01(\t\x12\x14\n\x0c\x64\x61te_request\x18\x06 \x01(\t\x12\x16\n\x0e\x64ownload_speed\x18\x07 \x01(\t\x12\x14\n\x0cupload_speed\x18\x08 \x01(\t\"5\n\x12\x43itySpeedsResponse\x12\x1f\n\ncitySpeeds\x18\x01 \x03(\x0b\x32\x0b.CitySpeeds2N\n\x11\x43itySpeedsService\x12\x39\n\x0e\x43itySpeedsInfo\x12\x12.CitySpeedsRequest\x1a\x13.CitySpeedsResponseb\x06proto3'
)




_CITYSPEEDSREQUEST = _descriptor.Descriptor(
  name='CitySpeedsRequest',
  full_name='CitySpeedsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='city_name', full_name='CitySpeedsRequest.city_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='CitySpeedsRequest.mean', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=85,
)


_CITYSPEEDS = _descriptor.Descriptor(
  name='CitySpeeds',
  full_name='CitySpeeds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CitySpeeds.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='CitySpeeds.country_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city_name', full_name='CitySpeeds.city_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region_code', full_name='CitySpeeds.region_code', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isp_name', full_name='CitySpeeds.isp_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_request', full_name='CitySpeeds.date_request', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='download_speed', full_name='CitySpeeds.download_speed', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_speed', full_name='CitySpeeds.upload_speed', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=270,
)


_CITYSPEEDSRESPONSE = _descriptor.Descriptor(
  name='CitySpeedsResponse',
  full_name='CitySpeedsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='citySpeeds', full_name='CitySpeedsResponse.citySpeeds', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=325,
)

_CITYSPEEDSRESPONSE.fields_by_name['citySpeeds'].message_type = _CITYSPEEDS
DESCRIPTOR.message_types_by_name['CitySpeedsRequest'] = _CITYSPEEDSREQUEST
DESCRIPTOR.message_types_by_name['CitySpeeds'] = _CITYSPEEDS
DESCRIPTOR.message_types_by_name['CitySpeedsResponse'] = _CITYSPEEDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CitySpeedsRequest = _reflection.GeneratedProtocolMessageType('CitySpeedsRequest', (_message.Message,), {
  'DESCRIPTOR' : _CITYSPEEDSREQUEST,
  '__module__' : 'cityspeeds_service_pb2'
  # @@protoc_insertion_point(class_scope:CitySpeedsRequest)
  })
_sym_db.RegisterMessage(CitySpeedsRequest)

CitySpeeds = _reflection.GeneratedProtocolMessageType('CitySpeeds', (_message.Message,), {
  'DESCRIPTOR' : _CITYSPEEDS,
  '__module__' : 'cityspeeds_service_pb2'
  # @@protoc_insertion_point(class_scope:CitySpeeds)
  })
_sym_db.RegisterMessage(CitySpeeds)

CitySpeedsResponse = _reflection.GeneratedProtocolMessageType('CitySpeedsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CITYSPEEDSRESPONSE,
  '__module__' : 'cityspeeds_service_pb2'
  # @@protoc_insertion_point(class_scope:CitySpeedsResponse)
  })
_sym_db.RegisterMessage(CitySpeedsResponse)



_CITYSPEEDSSERVICE = _descriptor.ServiceDescriptor(
  name='CitySpeedsService',
  full_name='CitySpeedsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=327,
  serialized_end=405,
  methods=[
  _descriptor.MethodDescriptor(
    name='CitySpeedsInfo',
    full_name='CitySpeedsService.CitySpeedsInfo',
    index=0,
    containing_service=None,
    input_type=_CITYSPEEDSREQUEST,
    output_type=_CITYSPEEDSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CITYSPEEDSSERVICE)

DESCRIPTOR.services_by_name['CitySpeedsService'] = _CITYSPEEDSSERVICE

# @@protoc_insertion_point(module_scope)
