# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import countrypackageloss_service_pb2 as countrypackageloss__service__pb2


class CountryPackageLossServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountryPackageLossInfo = channel.unary_unary(
                '/CountryPackageLossService/CountryPackageLossInfo',
                request_serializer=countrypackageloss__service__pb2.CountryPackageLossRequest.SerializeToString,
                response_deserializer=countrypackageloss__service__pb2.CountryPackageLossResponse.FromString,
                )


class CountryPackageLossServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountryPackageLossInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountryPackageLossServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountryPackageLossInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CountryPackageLossInfo,
                    request_deserializer=countrypackageloss__service__pb2.CountryPackageLossRequest.FromString,
                    response_serializer=countrypackageloss__service__pb2.CountryPackageLossResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CountryPackageLossService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CountryPackageLossService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountryPackageLossInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CountryPackageLossService/CountryPackageLossInfo',
            countrypackageloss__service__pb2.CountryPackageLossRequest.SerializeToString,
            countrypackageloss__service__pb2.CountryPackageLossResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
