# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countrypackageloss_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countrypackageloss_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n countrypackageloss_service.proto\"@\n\x19\x43ountryPackageLossRequest\x12\x10\n\x08isp_name\x18\x01 \x01(\t\x12\x11\n\tmean\x18\x02 \x01(\x08\"}\n\x12\x43ountryPackageLoss\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x10\n\x08isp_name\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61te_request\x18\x04 \x01(\t\x12\x13\n\x0bpacket_loss\x18\x05 \x01(\t\"M\n\x1a\x43ountryPackageLossResponse\x12/\n\x12\x63ountryPackageLoss\x18\x01 \x03(\x0b\x32\x13.CountryPackageLoss2n\n\x19\x43ountryPackageLossService\x12Q\n\x16\x43ountryPackageLossInfo\x12\x1a.CountryPackageLossRequest\x1a\x1b.CountryPackageLossResponseb\x06proto3'
)




_COUNTRYPACKAGELOSSREQUEST = _descriptor.Descriptor(
  name='CountryPackageLossRequest',
  full_name='CountryPackageLossRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='isp_name', full_name='CountryPackageLossRequest.isp_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='CountryPackageLossRequest.mean', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=100,
)


_COUNTRYPACKAGELOSS = _descriptor.Descriptor(
  name='CountryPackageLoss',
  full_name='CountryPackageLoss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryPackageLoss.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='CountryPackageLoss.country_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isp_name', full_name='CountryPackageLoss.isp_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_request', full_name='CountryPackageLoss.date_request', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='packet_loss', full_name='CountryPackageLoss.packet_loss', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=227,
)


_COUNTRYPACKAGELOSSRESPONSE = _descriptor.Descriptor(
  name='CountryPackageLossResponse',
  full_name='CountryPackageLossResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='countryPackageLoss', full_name='CountryPackageLossResponse.countryPackageLoss', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=306,
)

_COUNTRYPACKAGELOSSRESPONSE.fields_by_name['countryPackageLoss'].message_type = _COUNTRYPACKAGELOSS
DESCRIPTOR.message_types_by_name['CountryPackageLossRequest'] = _COUNTRYPACKAGELOSSREQUEST
DESCRIPTOR.message_types_by_name['CountryPackageLoss'] = _COUNTRYPACKAGELOSS
DESCRIPTOR.message_types_by_name['CountryPackageLossResponse'] = _COUNTRYPACKAGELOSSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryPackageLossRequest = _reflection.GeneratedProtocolMessageType('CountryPackageLossRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYPACKAGELOSSREQUEST,
  '__module__' : 'countrypackageloss_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryPackageLossRequest)
  })
_sym_db.RegisterMessage(CountryPackageLossRequest)

CountryPackageLoss = _reflection.GeneratedProtocolMessageType('CountryPackageLoss', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYPACKAGELOSS,
  '__module__' : 'countrypackageloss_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryPackageLoss)
  })
_sym_db.RegisterMessage(CountryPackageLoss)

CountryPackageLossResponse = _reflection.GeneratedProtocolMessageType('CountryPackageLossResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYPACKAGELOSSRESPONSE,
  '__module__' : 'countrypackageloss_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryPackageLossResponse)
  })
_sym_db.RegisterMessage(CountryPackageLossResponse)



_COUNTRYPACKAGELOSSSERVICE = _descriptor.ServiceDescriptor(
  name='CountryPackageLossService',
  full_name='CountryPackageLossService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=308,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountryPackageLossInfo',
    full_name='CountryPackageLossService.CountryPackageLossInfo',
    index=0,
    containing_service=None,
    input_type=_COUNTRYPACKAGELOSSREQUEST,
    output_type=_COUNTRYPACKAGELOSSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTRYPACKAGELOSSSERVICE)

DESCRIPTOR.services_by_name['CountryPackageLossService'] = _COUNTRYPACKAGELOSSSERVICE

# @@protoc_insertion_point(module_scope)
