# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import countrytotaltests_service_pb2 as countrytotaltests__service__pb2


class CountryTotalTestsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountryTotalTestsInfo = channel.unary_unary(
                '/CountryTotalTestsService/CountryTotalTestsInfo',
                request_serializer=countrytotaltests__service__pb2.CountryTotalTestsRequest.SerializeToString,
                response_deserializer=countrytotaltests__service__pb2.CountryTotalTestsResponse.FromString,
                )


class CountryTotalTestsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CountryTotalTestsInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountryTotalTestsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountryTotalTestsInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CountryTotalTestsInfo,
                    request_deserializer=countrytotaltests__service__pb2.CountryTotalTestsRequest.FromString,
                    response_serializer=countrytotaltests__service__pb2.CountryTotalTestsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CountryTotalTestsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CountryTotalTestsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CountryTotalTestsInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CountryTotalTestsService/CountryTotalTestsInfo',
            countrytotaltests__service__pb2.CountryTotalTestsRequest.SerializeToString,
            countrytotaltests__service__pb2.CountryTotalTestsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
