# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countrytotaltests_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countrytotaltests_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1f\x63ountrytotaltests_service.proto\"0\n\x18\x43ountryTotalTestsRequest\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\"h\n\x11\x43ountryTotalTests\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x12\n\ntests_date\x18\x03 \x01(\t\x12\x13\n\x0btotal_tests\x18\x04 \x01(\t\"J\n\x19\x43ountryTotalTestsResponse\x12-\n\x11\x63ountryTotalTests\x18\x01 \x03(\x0b\x32\x12.CountryTotalTests2j\n\x18\x43ountryTotalTestsService\x12N\n\x15\x43ountryTotalTestsInfo\x12\x19.CountryTotalTestsRequest\x1a\x1a.CountryTotalTestsResponseb\x06proto3'
)




_COUNTRYTOTALTESTSREQUEST = _descriptor.Descriptor(
  name='CountryTotalTestsRequest',
  full_name='CountryTotalTestsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryTotalTestsRequest.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=83,
)


_COUNTRYTOTALTESTS = _descriptor.Descriptor(
  name='CountryTotalTests',
  full_name='CountryTotalTests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryTotalTests.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='CountryTotalTests.country_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tests_date', full_name='CountryTotalTests.tests_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_tests', full_name='CountryTotalTests.total_tests', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=189,
)


_COUNTRYTOTALTESTSRESPONSE = _descriptor.Descriptor(
  name='CountryTotalTestsResponse',
  full_name='CountryTotalTestsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='countryTotalTests', full_name='CountryTotalTestsResponse.countryTotalTests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=265,
)

_COUNTRYTOTALTESTSRESPONSE.fields_by_name['countryTotalTests'].message_type = _COUNTRYTOTALTESTS
DESCRIPTOR.message_types_by_name['CountryTotalTestsRequest'] = _COUNTRYTOTALTESTSREQUEST
DESCRIPTOR.message_types_by_name['CountryTotalTests'] = _COUNTRYTOTALTESTS
DESCRIPTOR.message_types_by_name['CountryTotalTestsResponse'] = _COUNTRYTOTALTESTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryTotalTestsRequest = _reflection.GeneratedProtocolMessageType('CountryTotalTestsRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYTOTALTESTSREQUEST,
  '__module__' : 'countrytotaltests_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryTotalTestsRequest)
  })
_sym_db.RegisterMessage(CountryTotalTestsRequest)

CountryTotalTests = _reflection.GeneratedProtocolMessageType('CountryTotalTests', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYTOTALTESTS,
  '__module__' : 'countrytotaltests_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryTotalTests)
  })
_sym_db.RegisterMessage(CountryTotalTests)

CountryTotalTestsResponse = _reflection.GeneratedProtocolMessageType('CountryTotalTestsResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYTOTALTESTSRESPONSE,
  '__module__' : 'countrytotaltests_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryTotalTestsResponse)
  })
_sym_db.RegisterMessage(CountryTotalTestsResponse)



_COUNTRYTOTALTESTSSERVICE = _descriptor.ServiceDescriptor(
  name='CountryTotalTestsService',
  full_name='CountryTotalTestsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=267,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountryTotalTestsInfo',
    full_name='CountryTotalTestsService.CountryTotalTestsInfo',
    index=0,
    containing_service=None,
    input_type=_COUNTRYTOTALTESTSREQUEST,
    output_type=_COUNTRYTOTALTESTSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTRYTOTALTESTSSERVICE)

DESCRIPTOR.services_by_name['CountryTotalTestsService'] = _COUNTRYTOTALTESTSSERVICE

# @@protoc_insertion_point(module_scope)
