# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countrydistanceclientserver_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countrydistanceclientserver_service.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n)countrydistanceclientserver_service.proto\"M\n\"CountryDistanceClientServerRequest\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x11\n\tmean\x18\x02 \x01(\x08\"\x9e\x01\n\x1b\x43ountryDistanceClientServer\x12\x14\n\x0c\x63ountry_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63ountry_code\x18\x02 \x01(\t\x12\x10\n\x08isp_name\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x61te_request\x18\x04 \x01(\t\x12\x13\n\x0btotal_tests\x18\x05 \x01(\t\x12\x16\n\x0e\x64istance_miles\x18\x06 \x01(\t\"h\n#CountryDistanceClientServerResponse\x12\x41\n\x1b\x63ountryDistanceClientServer\x18\x01 \x03(\x0b\x32\x1c.CountryDistanceClientServer2\x92\x01\n\"CountryDistanceClientServerService\x12l\n\x1f\x43ountryDistanceClientServerInfo\x12#.CountryDistanceClientServerRequest\x1a$.CountryDistanceClientServerResponseb\x06proto3'
)




_COUNTRYDISTANCECLIENTSERVERREQUEST = _descriptor.Descriptor(
  name='CountryDistanceClientServerRequest',
  full_name='CountryDistanceClientServerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryDistanceClientServerRequest.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mean', full_name='CountryDistanceClientServerRequest.mean', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=122,
)


_COUNTRYDISTANCECLIENTSERVER = _descriptor.Descriptor(
  name='CountryDistanceClientServer',
  full_name='CountryDistanceClientServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='country_name', full_name='CountryDistanceClientServer.country_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_code', full_name='CountryDistanceClientServer.country_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isp_name', full_name='CountryDistanceClientServer.isp_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date_request', full_name='CountryDistanceClientServer.date_request', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_tests', full_name='CountryDistanceClientServer.total_tests', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distance_miles', full_name='CountryDistanceClientServer.distance_miles', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=283,
)


_COUNTRYDISTANCECLIENTSERVERRESPONSE = _descriptor.Descriptor(
  name='CountryDistanceClientServerResponse',
  full_name='CountryDistanceClientServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='countryDistanceClientServer', full_name='CountryDistanceClientServerResponse.countryDistanceClientServer', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=389,
)

_COUNTRYDISTANCECLIENTSERVERRESPONSE.fields_by_name['countryDistanceClientServer'].message_type = _COUNTRYDISTANCECLIENTSERVER
DESCRIPTOR.message_types_by_name['CountryDistanceClientServerRequest'] = _COUNTRYDISTANCECLIENTSERVERREQUEST
DESCRIPTOR.message_types_by_name['CountryDistanceClientServer'] = _COUNTRYDISTANCECLIENTSERVER
DESCRIPTOR.message_types_by_name['CountryDistanceClientServerResponse'] = _COUNTRYDISTANCECLIENTSERVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CountryDistanceClientServerRequest = _reflection.GeneratedProtocolMessageType('CountryDistanceClientServerRequest', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYDISTANCECLIENTSERVERREQUEST,
  '__module__' : 'countrydistanceclientserver_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryDistanceClientServerRequest)
  })
_sym_db.RegisterMessage(CountryDistanceClientServerRequest)

CountryDistanceClientServer = _reflection.GeneratedProtocolMessageType('CountryDistanceClientServer', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYDISTANCECLIENTSERVER,
  '__module__' : 'countrydistanceclientserver_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryDistanceClientServer)
  })
_sym_db.RegisterMessage(CountryDistanceClientServer)

CountryDistanceClientServerResponse = _reflection.GeneratedProtocolMessageType('CountryDistanceClientServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _COUNTRYDISTANCECLIENTSERVERRESPONSE,
  '__module__' : 'countrydistanceclientserver_service_pb2'
  # @@protoc_insertion_point(class_scope:CountryDistanceClientServerResponse)
  })
_sym_db.RegisterMessage(CountryDistanceClientServerResponse)



_COUNTRYDISTANCECLIENTSERVERSERVICE = _descriptor.ServiceDescriptor(
  name='CountryDistanceClientServerService',
  full_name='CountryDistanceClientServerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=392,
  serialized_end=538,
  methods=[
  _descriptor.MethodDescriptor(
    name='CountryDistanceClientServerInfo',
    full_name='CountryDistanceClientServerService.CountryDistanceClientServerInfo',
    index=0,
    containing_service=None,
    input_type=_COUNTRYDISTANCECLIENTSERVERREQUEST,
    output_type=_COUNTRYDISTANCECLIENTSERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COUNTRYDISTANCECLIENTSERVERSERVICE)

DESCRIPTOR.services_by_name['CountryDistanceClientServerService'] = _COUNTRYDISTANCECLIENTSERVERSERVICE

# @@protoc_insertion_point(module_scope)
